# Generated by Django 3.2.8 on 2022-11-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('idAporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('idCultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.agricultor')),
            ],
        ),
        migrations.CreateModel(
            name='LineaConsulta',
            fields=[
                ('idLineaConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('consulta', models.CharField(max_length=50)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.agricultor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('idRecomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.agricultor')),
                ('aporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.aporte')),
                ('lineaConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.lineaconsulta')),
            ],
        ),
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('idExperto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aporte',
            name='experto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.experto'),
        ),
        migrations.AddField(
            model_name='agricultor',
            name='experto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.experto'),
        ),
        migrations.AddField(
            model_name='agricultor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agropro.usuario'),
        ),
    ]
